//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isk
    {
        public int Isk_ID { get; set; }
        public Nullable<int> Isk_number { get; set; }
        public Nullable<System.DateTime> Isk_date { get; set; }
        public Nullable<int> Isk_Summ { get; set; }
        public string Isk_Statuse { get; set; }
    }
}
