//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strahovie_Companii
    {
        public int Company_ID { get; set; }
        public string Company_name { get; set; }
        public string Adress { get; set; }
        public string Contacts { get; set; }
    }
}
