//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strahovie_Polici
    {
        public int Police_ID { get; set; }
        public Nullable<int> Police_Number { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public Nullable<int> summ { get; set; }
        public string status { get; set; }
    }
}
